# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ninety-Plus of Blue
tagline:             "an aesthete's guide to shouting in public"
description:         "An NYCFC blog on football slash soccer slash literature slash aesthetics."
url:                 http://ninety-plus-of-blue.github.io

# About/contact
author:
  name:              Phillip R. Polefrone
  url:               https://twitter.com/polefrone
  email:             prmpolefrone@gmail.com

# Custom vars
version:             1.0.0

# Pagination

paginate: 3
paginate_path: "/page:num"